# 게이트웨이 서버 포트
server.port=8080

# 이 서비스의 이름
spring.application.name=gateway-service

# 유레카 서버 주소 (discovery-service에 등록하러 감)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 라우팅 설정 - 요청을 어느 서비스로 보낼지
# /auth/** 경로로 오는 요청은 auth-service로 라우팅
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# /plant/** 경로로 오는 요청은 plant-service로 라우팅
spring.cloud.gateway.routes[1].id=plant-service
spring.cloud.gateway.routes[1].uri=lb://plant-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/plant/**

# /sensor/** 경로로 오는 요청은 sensor-service로 라우팅
spring.cloud.gateway.routes[2].id=sensor-service
spring.cloud.gateway.routes[2].uri=lb://sensor-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/sensor/**

# /ai/** 경로로 오는 요청은 ai-service로 라우팅
spring.cloud.gateway.routes[3].id=ai-service
spring.cloud.gateway.routes[3].uri=lb://ai-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/ai/**


# 설명
# routes[3]                    → 4번째 라우팅 규칙 (0부터 시작)
#.id=ai-service                → 이 규칙의 이름 (구분용)
#.uri=lb://ai-service          → 어디로 보낼지 (유레카에 등록된 ai-service로)
#.predicates[0]=Path=/ai/**    → 언제 보낼지 (/ai/로 시작하는 요청이 오면)