spring.application.name=PlantCare
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/PlantCare
spring.datasource.username=root
spring.datasource.password=simjunhyun1@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=AIzaSyDhq6tqHH0yFvpF0of-Ebvq00n5d9X4XJs